// CaseWareUtil.csp functions.
export const GET_PROGRAM_PATH = "GET_PROGRAM_PATH";
export const GET_LAYOUT_PATH = "GET_LAYOUT_PATH";
export const GET_ROLES = "GET_ROLES";
export const GET_DOCUMENT_MANAGER_JSON = "GET_DOCUMENT_MANAGER_JSON";
export const GET_CASEWARE_DOCUMENT = "GET_CASEWARE_DOCUMENT";
export const GET_ALL_CASEWARE_DOCUMENTS = "GET_ALL_CASEWARE_DOCUMENTS";
export const GET_FOLDER_DOCUMENTS = "GET_FOLDER_DOCUMENTS";
export const GET_IS_MASTER_TEMPLATE = "GET_IS_MASTER_TEMPLATE";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_SYSTEM_INFO = "GET_SYSTEM_INFO";
export const OPEN_FILE_DIALOG = "OPEN_FILE_DIALOG";
export const UPLOAD_FILE = "UPLOAD_FILE";

// FileSystemUtil.csp functions.
export const FILE_EXISTS = "FILE_EXISTS";
export const FOLDER_EXISTS = "FOLDER_EXISTS";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const COPY_FOLDER = "COPY_FOLDER";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const DELETE_FILE = "DELETE_FILE";
export const COPY_FILE = "COPY_FILE";
export const GET_FILE = "GET_FILE";
export const SAVE_FILE = "SAVE_FILE";
export const LIST_FILES = "LIST_FILES";
export const LIST_FILES_WITH_EXTENSION = "LIST_FILES_WITH_EXTENSION";
export const GET_FILE_CONTENTS = "GET_FILE_CONTENTS";

// React DDB functions
export const LOAD_ALL_DATA = "DDB_LOAD_ALL_DATA";
export const LOAD_GENERAL_DATA = "DDB_LOAD_GENERAL_DATA";
export const LOAD_ALL_THEME_DATA = "DDB_LOAD_ALL_THEME_DATA";
export const LOAD_ALL_WIDGET_PRESET_DATA = "DDB_LOAD_ALL_WIDGET_PRESET_DATA";
export const LOAD_ALL_TAB_DATA = "DDB_LOAD_ALL_TAB_DATA";
export const LOAD_THEME_DATA = "DDB_LOAD_THEME_DATA";
export const LOAD_WIDGET_PRESET_DATA = "DDB_LOAD_WIDGET_PRESET_DATA";
export const LOAD_TAB_DATA = "DDB_LOAD_TAB_DATA";
export const SAVE_THEME = "DDB_SAVE_THEME";
export const SAVE_NAMESPACE = "DDB_SAVE_NAMESPACE";
export const SAVE_WIDGET_PRESET = "DDB_SAVE_WIDGET_PRESET";
export const SAVE_TAB = "DDB_SAVE_TAB";
export const ADD_THEME = "DDB_ADD_THEME";
export const ADD_NAMESPACE = "DDB_ADD_NAMESPACE";
export const ADD_WIDGET_PRESET = "DDB_ADD_WIDGET_PRESET";
export const ADD_TAB = "DDB_ADD_TAB";
export const REMOVE_THEME = "DDB_REMOVE_THEME";
export const REMOVE_NAMESPACE = "DDB_REMOVE_NAMESPACE";
export const REMOVE_WIDGET_PRESET = "DDB_REMOVE_WIDGET_PRESET";
export const REMOVE_TAB = "DDB_REMOVE_TAB";
export const SET_TAB_ORDER = "DDB_SET_TAB_ORDER";
export const SET_CURRENT_TAB = "DDB_SET_CURRENT_TAB";
export const SET_DEFAULT_NAMESPACE = "DDB_SET_DEFAULT_NAMESPACE";
export const SAVE_HEADER = "DDB_SAVE_HEADER";
export const SAVE_FOOTER = "DDB_SAVE_FOOTER";


export default {
    GET_PROGRAM_PATH,
    GET_LAYOUT_PATH,
    GET_ROLES,
    GET_DOCUMENT_MANAGER_JSON,
    GET_CASEWARE_DOCUMENT,
    GET_ALL_CASEWARE_DOCUMENTS,
    GET_FOLDER_DOCUMENTS,
    GET_IS_MASTER_TEMPLATE,
    GET_CURRENT_USER,
    GET_SYSTEM_INFO,
    OPEN_FILE_DIALOG,
    UPLOAD_FILE,
    FILE_EXISTS,
    FOLDER_EXISTS,
    CREATE_FOLDER,
    COPY_FOLDER,
    DELETE_FOLDER,
    DELETE_FILE,
    COPY_FILE,
    SAVE_FILE,
    LIST_FILES,
    LIST_FILES_WITH_EXTENSION,
    LOAD_ALL_DATA,
    LOAD_GENERAL_DATA,
    LOAD_ALL_THEME_DATA,
    LOAD_ALL_WIDGET_PRESET_DATA,
    LOAD_ALL_TAB_DATA,
    LOAD_THEME_DATA,
    LOAD_WIDGET_PRESET_DATA,
    LOAD_TAB_DATA,
    SAVE_THEME,
    SAVE_WIDGET_PRESET,
    SAVE_TAB,
    ADD_THEME,
    ADD_WIDGET_PRESET,
    ADD_TAB,
    REMOVE_THEME,
    REMOVE_WIDGET_PRESET,
    REMOVE_TAB,
    SET_TAB_ORDER,
    SET_CURRENT_TAB,
    SAVE_NAMESPACE,
    ADD_NAMESPACE,
    REMOVE_NAMESPACE,
    SET_DEFAULT_NAMESPACE,
    SAVE_HEADER,
    SAVE_FOOTER,
};
