// Base modals
export const MODAL_WRAPPER = "MODAL_WRAPPER";
export const ASSERTION_BASE = "ASSERTION_BASE";

// General modals
export const ERROR_ASSERTION = "ERROR_ASSERTION";
export const INFO_ASSERTION = "INFO_ASSERTION";
export const WARNING_ASSERTION = "WARNING_ASSERTION";
export const COLOR_PICKER = "COLOR_PICKER";
export const CONFIRM = "CONFIRM";

// Tab modals
export const TAB_CONFIGURATION_BASE = "TAB_CONFIGURATION_BASE";
export const TAB_MANAGER = "TAB_MANAGER";
export const DASHBOARD_SETTINGS = "DASHBOARD_SETTINGS";
export const TAB_ADD = "TAB_ADD";
export const TAB_EDIT = "TAB_EDIT";

// Widget Modals
export const WIDGET_PRESET_MANAGER = "WIDGET_PRESET_MANAGER";
export const WIDGET_PRESET_ADD_SELECTOR = "WIDGET_PRESET_ADD_SELECTOR";
export const WIDGET_PRESET_CONFIGURATION_BASE = "WIDGET_PRESET_CONFIGURATION_BASE";
export const WIDGET_PRESET_ADD = "WDIGET_PRESET_ADD";
export const WIDGET_PRESET_EDIT = "WIDGET_PRESET_EDIT";
export const TAG_ADD = "TAG_ADD";
export const WORKFLOW_BUTTON_CONFIGURATION_BASE = "WORKFLOW_BUTTON_CONFIGURATION_BASE";
export const WORKFLOW_BUTTON_ADD = "WORKFLOW_BUTTON_ADD";
export const WORKFLOW_BUTTON_EDIT = "WORKFLOW_BUTTON_EDIT";
export const WORKFLOW_LAUNCH_MAPPING = "WORKFLOW_LAUNCH_MAPPING";

// Header/footer Modals
export const MARGINALS_CONFIGURATION_BASE = "MARGINALS_CONFIGURATION_BASE";
export const HEADER_CONFIGURATION = "HEADER_CONFIGURATION";
export const FOOTER_CONFIGURATION = "FOOTER_CONFIGURATION";

export default {
    MODAL_WRAPPER,
    ASSERTION_BASE,
    ERROR_ASSERTION,
    INFO_ASSERTION,
    WARNING_ASSERTION,
    COLOR_PICKER,
    CONFIRM,
    TAB_CONFIGURATION_BASE,
    DASHBOARD_SETTINGS,
    TAB_MANAGER,
    TAB_ADD,
    TAB_EDIT,
    WIDGET_PRESET_MANAGER,
    WIDGET_PRESET_ADD_SELECTOR,
    WIDGET_PRESET_CONFIGURATION_BASE,
    WIDGET_PRESET_ADD,
    WIDGET_PRESET_EDIT,
    TAG_ADD,
    WORKFLOW_BUTTON_CONFIGURATION_BASE,
    WORKFLOW_BUTTON_ADD,
    WORKFLOW_BUTTON_EDIT,
    WORKFLOW_LAUNCH_MAPPING,
    MARGINALS_CONFIGURATION_BASE,
    HEADER_CONFIGURATION,
    FOOTER_CONFIGURATION,
};

