export const modalEvents = {
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    DID_CONTAINER_MOUNT: "MODAL_DID_CONTAINER_MOUNT",
    WILL_CONTAINER_UNMOUNT: "MODAL_WILL_CONTAINER_UNMOUNT"
};

export const loadingScreenEvents = {
    SHOW_LOADING: "SHOW_LOADING_SCREEN",
    HIDE_LOADING: "HIDE_LOADING_SCREEN",
    SET_STATUS: "SET_LOADING_STATUS",
    DID_CONTAINER_MOUNT: "LOADING_DID_CONTAINER_MOUNT",
    WILL_CONTAINER_UNMOUNT: "LOADING_WILL_CONTAINER_UNMOUNT"
};

export const contextMenuEvents = {
    SHOW_CONTEXT_MENU: "SHOW_CONTEXT_MENU",
    HIDE_CONTEXT_MENU: "HIDE_CONTEXT_MENU",
    DID_CONTAINER_MOUNT: "CONTEXT_DID_CONTAINER_MOUNT",
    WILL_CONTAINER_UNMOUNT: "CONTEXT_WILL_CONTAINER_UNMOUNT"
};

export default {
    modalEvents,
    loadingScreenEvents,
    contextMenuEvents
};