import * as LANG_CONST from "constants/language";

export const HTML_CONTAINER_WIDGET = LANG_CONST.HTML_CONTAINER_WIDGET_DISPLAY_NAME;
export const RICH_TEXT_WIDGET = LANG_CONST.RICH_TEXT_WIDGET_DISPLAY_NAME;
export const WORKFLOW_WIDGET = LANG_CONST.WORKFLOW_WIDGET_DISPLAY_NAME;
export const MARGINALS_WIDGET = LANG_CONST.MARGINALS_WIDGET_DISPLAY_NAME;

export default {
    HTML_CONTAINER_WIDGET,
    RICH_TEXT_WIDGET,
    WORKFLOW_WIDGET,
    MARGINALS_WIDGET,
};