export const HTML_CONTAINER_WIDGET = "HTML_CONTAINER_WIDGET";
export const RICH_TEXT_WIDGET = "RICH_TEXT_WIDGET";
export const WORKFLOW_WIDGET = "WORKFLOW_WIDGET";
export const MARGINALS_WIDGET = "MARGINALS_WIDGET";

export default {
    HTML_CONTAINER_WIDGET,
    RICH_TEXT_WIDGET,
    WORKFLOW_WIDGET,
    MARGINALS_WIDGET,
};